name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [synchronize]
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: dotnet restore

      - name: Cache .NET dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use cached .NET dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Run tests
        run: dotnet test --no-restore

  release:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        run: echo "VERSION=0.1.0" >> $GITHUB_ENV

      - name: Generate Changelog
        uses: dnbkr/clog@v2
        with:
          githubToken: ${{ secrets.CI_BOT_TOKEN }}
          version: ${{ env.VERSION }}

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: v${{ env.VERSION }}
          tag_exists_error: false

      # Print result using the env variable.
      - run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v"${{ env.VERSION }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Pack NuGet artifacts
        run: dotnet pack -c Release -o ./nupkg

      - name: Publish NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: NuGetPackage
          path: ./nupkg/*.nupkg
          retention-days: 90

      - name: Publish to NuGet feed
        run: |
          for package in ./nupkg/*.nupkg; do
            dotnet nuget push "$package" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
          done